# Generated by Django 6.1 on 2026-09-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, help_text='The Job.Id UUID from the .NET backend.', unique=True)),
                ('embedding', models.JSONField(help_text='384-dim vector from sentence-transformers.')),
                ('keywords', models.JSONField(default=list, help_text='Extracted keywords (words > 3 chars) from the job text.')),
                ('job_data_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 of the job data. Used to detect edits.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SweepState',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_sweep_at', models.DateTimeField(auto_now_add=True)),
                ('jobs_scored', models.PositiveIntegerField(default=0)),
                ('users_processed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TalentProfileVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_user_id', models.CharField(db_index=True, help_text='The ASP.NET Identity user GUID from the .NET backend.', max_length=64, unique=True)),
                ('embedding', models.JSONField(help_text='384-dim vector from sentence-transformers.')),
                ('keywords', models.JSONField(default=list, help_text='Extracted keywords (words > 3 chars) from the profile text.')),
                ('profile_hash', models.CharField(db_index=True, help_text='SHA-256 of the profile text. Used to detect changes.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentJobScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_user_id', models.CharField(db_index=True, max_length=64)),
                ('job_id', models.UUIDField(db_index=True)),
                ('score', models.FloatField(help_text='Compatibility score 0-100.')),
                ('matched', models.JSONField(default=list)),
                ('missing', models.JSONField(default=list)),
                ('explanation', models.JSONField(default=dict)),
                ('talent_profile_hash', models.CharField(help_text='Hash of talent profile at scoring time.', max_length=64)),
                ('job_data_hash', models.CharField(help_text='Hash of job data at scoring time.', max_length=64)),
                ('scoring_version', models.CharField(default='1.0.0', help_text='Algorithm version used to compute this score.', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('talent_user_id', 'job_id')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_active', models.DateTimeField(db_index=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['-last_active'], name='matching_en_last_ac_8b79ec_idx')],
            },
        ),
    ]
