# Generated by Django 6.1 on 2026-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(db_index=True, help_text='The JobApplication.Id UUID from the .NET backend.', unique=True)),
                ('talent_user_id', models.CharField(db_index=True, help_text="The talent's user GUID.", max_length=64)),
                ('job_id', models.UUIDField(db_index=True, help_text='The Job.Id UUID from the .NET backend.')),
                ('status', models.CharField(choices=[('pending', 'Pending scoring'), ('scored', 'Scored'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('talent_data', models.JSONField(help_text='Full talent profile snapshot at time of application.')),
                ('job_data', models.JSONField(help_text='Full job data snapshot at time of application.')),
                ('score', models.FloatField(blank=True, help_text='Compatibility score 0-100.', null=True)),
                ('matched', models.JSONField(blank=True, default=list)),
                ('missing', models.JSONField(blank=True, default=list)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
