# Generated by Django 6.1 on 2026-09-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching_engine', '0002_applicationscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SweepState',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='matching_en_last_ac_8b79ec_idx',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
