# Generated by Django 6.1 on 2026-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('huggingface', 'Hugging Face')], max_length=32)),
                ('model', models.CharField(max_length=100)),
                ('feature', models.CharField(help_text="Which AI feature was used (e.g., 'resume_parsing', 'cover_letter').", max_length=50)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
