# Generated by Django 6.1 on 2026-09-10 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiClassificationRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(help_text='The exact JSON sent to Groq (model, messages, temperature, etc.).')),
                ('response_payload', models.JSONField(help_text='The exact JSON returned by Groq (full chat completion).')),
                ('model', models.CharField(help_text='Groq model used for this call.', max_length=128)),
                ('status', models.CharField(help_text="Outcome: 'ok', 'error', or 'uncategorized'.", max_length=32)),
                ('latency_ms', models.IntegerField(default=0, help_text='Milliseconds from request start to parsed response.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the Groq call happened.')),
            ],
            options={
                'verbose_name': 'AI classification raw call',
                'verbose_name_plural': 'AI classification raw calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiClassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='The .NET Job.Id (UUID string) that was classified.', max_length=64)),
                ('sector_slug', models.CharField(blank=True, default='', help_text='Canonical sector slug chosen by the LLM, or empty if uncategorized.', max_length=128)),
                ('sector_name', models.CharField(blank=True, default='', help_text='Canonical sector name chosen by the LLM, or empty if uncategorized.', max_length=256)),
                ('confidence', models.FloatField(blank=True, help_text='LLM confidence in the chosen sector (0..1), or null.', null=True)),
                ('reasoning', models.TextField(blank=True, default='', help_text='LLM reasoning for the chosen sector, or empty.')),
                ('categorized', models.BooleanField(help_text='True when the LLM assigned a real sector; False when uncategorized.')),
                ('original_sector_slug', models.CharField(blank=True, default='', help_text='Sector slug the job had before this classify call (sent by .NET).', max_length=128)),
                ('original_sector_name', models.CharField(blank=True, default='', help_text='Sector name the job had before this classify call (sent by .NET).', max_length=256)),
                ('ai_classified_at', models.DateTimeField(auto_now_add=True, help_text='When this classify call happened (moved here from Jobs.AiClassifiedAt).')),
                ('log_id', models.OneToOneField(help_text='The raw request/response row for this classify attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='classification_log', to='ai_service.aiclassificationraw')),
            ],
            options={
                'verbose_name': 'AI classification log',
                'verbose_name_plural': 'AI classification logs',
                'ordering': ['-ai_classified_at'],
            },
        ),
    ]
