# Generated by Django 6.1 on 2026-09-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_add_ai_classification_log_and_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiclassificationraw',
            name='est_tokens_sent',
            field=models.IntegerField(blank=True, help_text='Local tiktoken estimate of the request payload, computed before the call.', null=True),
        ),
        migrations.AddField(
            model_name='aiclassificationraw',
            name='jobs_sent',
            field=models.IntegerField(blank=True, help_text='How many jobs were in the whole classify batch this call was part of.', null=True),
        ),
        migrations.AddField(
            model_name='aiclassificationraw',
            name='tokens_received',
            field=models.IntegerField(blank=True, help_text='Exact completion tokens received (usage.completion_tokens from Groq), or null if unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='aiclassificationraw',
            name='tokens_sent',
            field=models.IntegerField(blank=True, help_text='Exact prompt tokens sent (usage.prompt_tokens from Groq), or null if unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='aiclassificationraw',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='Exact total tokens (usage.total_tokens from Groq), or null if unavailable.', null=True),
        ),
    ]
